DROP TABLE IF EXISTS "users_conferences";
DROP TABLE IF EXISTS "messages";
DROP TABLE IF EXISTS "authors_articles";
DROP TABLE IF EXISTS "articles";
DROP TABLE IF EXISTS "conferences";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "organizations";

CREATE TABLE "users"
(
    "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    "email"           VARCHAR(255)                             NOT NULL UNIQUE,
    "name"            VARCHAR(255)                             NOT NULL,
    "organization_id" INTEGER,
    PRIMARY KEY ("id")
);

CREATE TABLE "organizations"
(
    "id"   INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY ("id")
);

CREATE TABLE "conferences"
(
    "id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    "name"        VARCHAR(255) NOT NULL,
    "description" VARCHAR(255),
    "start_date"  TIMESTAMP,
    "end_date"    TIMESTAMP,
    PRIMARY KEY ("id")
);


CREATE TABLE "articles"
(
    "id"          INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    "title"       VARCHAR(255) NOT NULL,
    "description" VARCHAR(255),
    "filepath"    VARCHAR(255),
    PRIMARY KEY ("id")
);

CREATE TABLE "authors_articles"
(
    "user_id"    INTEGER NOT NULL,
    "article_id" INTEGER NOT NULL,
    PRIMARY KEY ("user_id", "article_id")
);

CREATE TABLE "messages"
(
    "id"           INTEGER      GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    "message_id"   INTEGER,
    "sender_id"    INTEGER      NOT NULL,
    "recipient_id" INTEGER      NOT NULL,
    "message"      VARCHAR(255) NOT NULL,
    "date"         TIMESTAMP    NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "users_conferences"
(
    "user_id"       INTEGER NOT NULL,
    "conference_id" INTEGER NOT NULL,
    PRIMARY KEY ("user_id", "conference_id")
);

ALTER TABLE "users"
    ADD FOREIGN KEY("organization_id") REFERENCES "organizations"("id")
        ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "authors_articles"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "authors_articles"
    ADD FOREIGN KEY("article_id") REFERENCES "articles"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "messages"
    ADD FOREIGN KEY("message_id") REFERENCES "messages"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "messages"
    ADD FOREIGN KEY("sender_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "messages"
    ADD FOREIGN KEY("recipient_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users_conferences"
    ADD FOREIGN KEY("conference_id") REFERENCES "conferences"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users_conferences"
    ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;