services:
  main-service:
    build: main-service
    container_name: main-service
    ports:
      - "9090:9090"
    depends_on:
      - main-db
      #- articles-db

  main-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
