spring:
  profiles:
    active: test
  application:
   name: statistics-service

  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
server:
  port: 9092


